razorserver:
  build: .
  volumes: 
    - /data/razor:/var/lib/razor
  links:
    - razordb
razordb:
  image: centos/postgresql-94-centos7
  volumes: 
    - /data/razor/pgsql:/var/lib/pgsql/data
  environment:
    POSTGRESQL_USER: razor
    POSTGRESQL_PASSWORD: mypass
    POSTGRESQL_DATABASE: razor_prd
    
