# This file is used in conjunction with Dockerfile in this git repo to run the 
#  razor app across two containers locally.
#  
razorserver:
  image: spam4kev/razor-server         #use this line and comment out the next to cut time on deploy
#  build: .                              #use this line and commend out the previous to get the latest build
  command: /etc/razor/razor-entrypoint.sh
  volumes: 
    - /data/razor:/var/lib/razor
  links:
    - razordb
    - pxeserver
  ports:
    - 8150:8150
razordb:
  image: centos/postgresql-94-centos7
  volumes: 
    - /data/razor/pgsql:/var/lib/pgsql/data
  environment:
    POSTGRESQL_USER: razor
    POSTGRESQL_PASSWORD: mypass
    POSTGRESQL_DATABASE: razor_prd
pxeserver:
  image: spam4kev/pxe
  cap_add:
    - NET_ADMIN
  working_dir: /tftpboot
  command: "wget http://boot.ipxe.org/undionly.kpxe && iptables -t nat -A POSTROUTING -j MASQUERADE && echo Waiting for pipework to give us the eth1 interface... && /pipework --wait && myIP=$(grep $(hostname) /etc/hosts | cut -d: -f2 | awk '{ print $1}') && mySUBNET=$(echo $myIP | cut -d '.' -f 1,2,3) && echo Starting DHCP+TFTP server... && dnsmasq --dhcp-match=IPXEBOOT,175 --interface=eth1 --dhcp-range=$mySUBNET.101,$mySUBNET.199,255.255.255.0,1h --dhcp-boot=net:IPXEBOOT,bootstrap.ipxe,$myIP --dhcp-boot=undionly.kpxe --enable-tftp --tftp-root=/tftpboot --no-daemon"
