# This file is used in conjunction with Dockerfile in this git repo to run the 
#  razor app across two containers locally.
#  
razorserver:
  image: spam4kev/razor-server         #use this line and comment out the next to cut time on deploy
#  build: .                              #use this line and commend out the previous to get the latest build
  command: /etc/razor/razor-entrypoint.sh
  volumes: 
    - /data/razor:/var/lib/razor
  links:
    - razordb
razordb:
  image: centos/postgresql-94-centos7
  volumes: 
    - /data/razor/pgsql:/var/lib/pgsql/data
  environment:
    POSTGRESQL_USER: razor
    POSTGRESQL_PASSWORD: mypass
    POSTGRESQL_DATABASE: razor_prd
