razorserver:
  build: .
  volumes: 
    - /data/razor-repo-store:/var/lib/razor/repo-store
  links:
    - db
razordb:
  image: centos/postgresql-94-centos7
  volumes: 
    - /data/pgsql:/var/lib/pgsql/data
  environment:
    POSTGRESQL_USER: razor
    POSTGRESQL_PASSWORD: mypass
    POSTGRESQL_DATABASE: razor_prd
    
