razorserver:
  image: spam4kev/razor-server 
  volumes: 
    - /data/razor:/var/lib/razor
  links:
    - razordb
razordb:
  image: spam4kev/razor-db
  volumes: 
    - /data/razor/pgsql:/var/lib/pgsql/data
  environment:
    POSTGRESQL_USER: razor
    POSTGRESQL_PASSWORD: mypass
    POSTGRESQL_DATABASE: razor_prd
